stretch:
  image: debian:stretch
  script:
    - apt-get -q update
    - apt-get -q -y dist-upgrade
    - apt-get -q -y install python3-yaml python3-retrying
    - ./buildd_test.py
sid:
  image: debian:sid
  script:
    - apt-get -q update
    - apt-get -q -y dist-upgrade
    - apt-get -q -y install python3-yaml python3-retrying
    - apt-get -q -y install mypy python3-pkg-resources
    - mypy --ignore-missing-imports --follow-imports=skip ./buildd.py
    - ./buildd_test.py
